image: maven:3.6.0-jdk-8

stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -s $M2_SETTINGS -Dorg.apache.activemq.artemis.core.io.aio.AIOSequentialFileFactory.DISABLED=AnythingNotNull clean install

deploy:
  stage: deploy
  only:
    - 2.9.0-PSI
  script:
    - mvn $MAVEN_CLI_OPTS -s $M2_SETTINGS -Dorg.apache.activemq.artemis.core.io.aio.AIOSequentialFileFactory.DISABLED=AnythingNotNull deploy 
